-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 0.9.2-alpha1
-- Diff date: 2018-12-20 17:28:13
-- Source model: otolithe
-- Database: otolithe
-- PostgreSQL version: 11.0

-- [ Diff summary ]
-- Dropped objects: 0
-- Created objects: 5
-- Changed objects: 2
-- Truncated tables: 0

SET search_path=public,pg_catalog,otolithe;
-- ddl-end --


-- object: otolithe.metadatatype | type: TABLE --
-- DROP TABLE IF EXISTS otolithe.metadatatype CASCADE;
CREATE TABLE otolithe.metadatatype (
	metadatatype_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	metadatatype_name varchar NOT NULL,
	metadatatype_comment varchar,
	metadatatype_description bytea,
	is_array boolean DEFAULT f,
	metatadatatype_json json,
	CONSTRAINT metadatatype_pk PRIMARY KEY (metadatatype_id)

);
-- ddl-end --
COMMENT ON COLUMN otolithe.metadatatype.metadatatype_name IS 'Nom du type de métadonnées';
-- ddl-end --
COMMENT ON COLUMN otolithe.metadatatype.metadatatype_comment IS 'Description du type de métadonnées';
-- ddl-end --
COMMENT ON COLUMN otolithe.metadatatype.metadatatype_description IS 'Description externe du jeu de métadonnées (fichier PDF attaché, par exemple)';
-- ddl-end --
COMMENT ON COLUMN otolithe.metadatatype.is_array IS 'Définit si les données sont sous forme de tableau ou uniques';
-- ddl-end --
COMMENT ON COLUMN otolithe.metadatatype.metatadatatype_json IS 'Description JSON au format AlpacaJS du type de métadonnées';
-- ddl-end --
ALTER TABLE otolithe.metadatatype OWNER TO postgres;
-- ddl-end --

-- object: otolithe.piecemetadata | type: TABLE --
-- DROP TABLE IF EXISTS otolithe.piecemetadata CASCADE;
CREATE TABLE otolithe.piecemetadata (
	metadatapiece_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	piece_id integer NOT NULL,
	metadata_id integer NOT NULL,
	metadata json,
	piecemetadata_date timestamp,
	piecemetadata_comment varchar,
	CONSTRAINT piecemetadata_pk PRIMARY KEY (metadatapiece_id)

);
-- ddl-end --
COMMENT ON TABLE otolithe.piecemetadata IS 'Métadonnées rattachées à une pièce calcifiée';
-- ddl-end --
COMMENT ON COLUMN otolithe.piecemetadata.metadata IS 'Valeurs associées, au format Json';
-- ddl-end --
COMMENT ON COLUMN otolithe.piecemetadata.piecemetadata_date IS 'Date d''acquisition des informations';
-- ddl-end --
COMMENT ON COLUMN otolithe.piecemetadata.piecemetadata_comment IS 'Commentaires libres';
-- ddl-end --
ALTER TABLE otolithe.piecemetadata OWNER TO postgres;
-- ddl-end --



-- [ Changed objects ] --
ALTER DATABASE otolithe OWNER TO quinton;
-- ddl-end --
COMMENT ON COLUMN otolithe.photolecture.commentaire IS 'Commentaire sur la lecture';
-- ddl-end --


-- [ Created foreign keys ] --
-- object: piece_fk | type: CONSTRAINT --
-- ALTER TABLE otolithe.piecemetadata DROP CONSTRAINT IF EXISTS piece_fk CASCADE;
ALTER TABLE otolithe.piecemetadata ADD CONSTRAINT piece_fk FOREIGN KEY (piece_id)
REFERENCES otolithe.piece (piece_id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: metadatatype_fk | type: CONSTRAINT --
-- ALTER TABLE otolithe.piecemetadata DROP CONSTRAINT IF EXISTS metadatatype_fk CASCADE;
ALTER TABLE otolithe.piecemetadata ADD CONSTRAINT metadatatype_fk FOREIGN KEY (metadata_id)
REFERENCES otolithe.metadatatype (metadatatype_id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

